### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by NigelGreenway** [auraphp/Aura.Filter#101]
Hey,

A great package, but wondered what the timeline is for supporting php 7? There is a class `Bool` which is now a reserved keyword in php7.

**Comment by harikt** [comment]
Hey @NigelGreenway , 

You may be probably looking at 1.x version. There is a 2.x version in beta which is compatible with PHP7.

Hope that helps!

Thank you

**Comment by NigelGreenway** [comment]
Ah, I think you are right @harikt as it is now called Boolean.

-- Sorry :)

**Comment by harikt** [comment]
@NigelGreenway no issues. Happy to help :) .
