### ISSUE TITLE
isNotBlank gone

### ISSUE THREAD

**Issue by designermonkey** [auraphp/Aura.Filter#112]
https://github.com/auraphp/Aura.Filter/blob/2.0.0/src/Spec/ValidateSpec.php

The `isNotBlank` rule has vanished. The docs still say to use it.

How can I test a field is not blank and apply a specific error message to it if it is?

**Comment by pmjones** [comment]
`isNotBlank()` is introduced in the current 2.x branch, not the 2.0.0 tag; you can look for it in the next release (2.1), or use the 2.x development branch.

Sorry for the hassle!

**Comment by designermonkey** [comment]
Ok, thanks.

**Comment by harikt** [comment]
@pmjones how about a 2.1 release then ;) .

Thank you.

**Comment by pmjones** [comment]
Thought I'd wait on @jakejohns to clear up the case-related stuff, unless we're in a hurry. :-)
