### ISSUE TITLE
dev branch isNotBlank not working as expected

### ISSUE THREAD

**Issue by designermonkey** [auraphp/Aura.Filter#113]
My expectation is that `isNotBlank` would give me an error message if the passed in field was blank.

When I pass a field in that has a value, this validation returns an error.

**Comment by designermonkey** [comment]
current workaround is: `is('strlenMin', 1)`

**Comment by pmjones** [comment]
Insufficient testing on my part. Working through it now.

**Comment by pmjones** [comment]
All right, let's try this again. Newest push to 2.x branch has modified logic in ValidateSpec and SanitizeSpec, and better testing around isNotBlank(). Let me know if it works for you.

**Comment by harikt** [comment]
2.1 released. Hopefully things will be working fine. Can we close the issue ?

**Comment by pmjones** [comment]
@designermonkey Take a look and let us know. Sorry for the hassle.

**Comment by designermonkey** [comment]
Sorry, will do on Monday as it's a client project.

**Comment by pmjones** [comment]
At your convenience. :-)

**Comment by pmjones** [comment]
@designermonkey How's it looking?

**Comment by designermonkey** [comment]
I can confirm it is working :D Sorry for the delay.

**Comment by pmjones** [comment]
Not at all! Thanks for having reported it in the first place.
