### ISSUE TITLE
Sanitize to Field If Blank?

### ISSUE THREAD

**Issue by jakejohns** [auraphp/Aura.Filter#119]
Often I wish to set a field (ie. `slug`) to the value of another field (ie. title) _if the former is blank_, then sanitize it further. I think I can accomplish this now with some magic strings like this:

``` php
$filter->sanitize('slug')->useBlankValue('FIELD_IS_BLANK');
$filter->sanitize('slug')->to('callback', function ($subject, $field) {
    if ($subject->$field == 'FIELD_IS_BLANK') {
        $subject->$field = $subject->title;
    }
    return true;
});
$filter->sanitize('slug')->to('uppercase');


$data = [
    'slug' => '',
    'title' => 'some thing here'
];

var_dump($filter->apply($data));
var_dump($data);
```

But that's kind of awkward/magical/weird.

Any suggestions? Think we need a PR?

I was thinking about patching the `SanatizeSpec` to be able to pass a `callable` to `useBlankValue` that would take the subject as an arg, but i don't actually think that's the way.

ie.:

``` php
    //  SanitizeSpec::__invoke
    public function __invoke($subject)
    {
        if (! $this->subjectFieldIsBlank($subject)) {
            return parent::__invoke($subject);
        }

        if (! $this->allow_blank) {
            return false;
        }

        $blank = $this->blank_value;

        if (is_callable($blank)) {
            $blank = $blank($subject, $this->field);
        }

        $field = $this->field;
        $subject->$field = $blank;
        return true;
    }

// filter
$filter->sanitize('slug')->useBlankValue(
    function ($subject, $field) {
        return $subject->title;
    }
);
```

Maybe what I want isn't really a "blank" value, but a "defaultTo" or something? and should encompass a new set of logic?

``` php
//  SanitizeSpec::__invoke
    public function __invoke($subject)
    {
        if (! $this->subjectFieldIsBlank($subject)) {
            return parent::__invoke($subject);
        }
        if ($defaultField = $this->defaultTo) {
            $subject->$field = $subject->$default;
            return parent::__invoke($subject);
        }
        // ...
    }

```

Thoughts?

**Comment by pmjones** [comment]
> I was thinking about patching the SanatizeSpec to be able to pass a callable to useBlankValue that would take the subject as an arg, but i don't actually think that's the way.

I wonder if an added method `useBlankField()` (or something like that) would be useful here, to indicate "if blank, use the value from this field".

**Comment by pmjones** [comment]
@jakejohns Any further thoughts here?
