### ISSUE TITLE
JsonSerializable

### ISSUE THREAD

**Issue by designermonkey** [auraphp/Aura.Filter#120]
I've just come across a great scenario where I need to get all of the failure data as json for a vue.js component to take over.

Would it be a good idea to implement `JsonSerializable` in the Failure class?

**Comment by harikt** [comment]
Do you mean to validate json ? Something like https://github.com/Seldaek/jsonlint ?

**Comment by designermonkey** [comment]
No, I mean so that we can just use

``` php

$json = json_encode($validator->getFailures());
```

Currently it returns a FailureCollection of Failure objects. It would be great if it could just be serializable as json from the objects.

**Comment by designermonkey** [comment]
Here is the spec for the interface: http://php.net/manual/en/class.jsonserializable.php

**Comment by pmjones** [comment]
@designermonkey That seems like a straightforward change. Send a PR for that and I'll review.

**Comment by designermonkey** [comment]
ok (hopes I get some time to myself to do it asap) :)

**Comment by harikt** [comment]
As this is fixed with #121 . Closing the issue.
