### ISSUE TITLE
Sanitize is causing validation error

### ISSUE THREAD

**Issue by designermonkey** [auraphp/Aura.Filter#123]
Maybe I've missed something, and hopefully this can be closed pretty quickly.

```
        $f->sanitize('member-url')->toBlankOr('callback', function ($subject, $field) {
            if (strlen($subject->$field) > 0 && strpos($subject->$field, 'http://') !== false) {
                $subject->$field = 'http://'.$subject->$field;
            }
        });
        $f->validate('member-url')->isBlankOr('url')->asSoftRule('Your website should be a valid url.');
```

Basically, if the field has a value, I want to ensure it starts with `http`, but this combination always gives me:

`member-url should have sanitized to callback(*Closure*)`

Can anyone triage what's wrong here?

**Comment by pmjones** [comment]
Try `return true` to indicate the sanitizing worked (i.e., inside the closure).

**Comment by harikt** [comment]
also @designermonkey if you have questions / doubts I wished if you could write to google groups. There will be other people also willing to help.

Thank you for your consideration.

**Comment by designermonkey** [comment]
Ok thanks @pmjones
