### ISSUE TITLE
idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated

### ISSUE THREAD

**Issue by merlindiavova** [auraphp/Aura.Filter#138]
PHP 7.2 is reporting idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated.
src: src/Rule/Validate/Email.php:413

Are there any plans to update this - I could do a pull request?

**Comment by harikt** [comment]
Send a PR to 3.x branch.

**Comment by harikt** [comment]
Oh and if there is no BC break, you can send to 2.x as well.

**Comment by harikt** [comment]
I think this is no longer an issue for all tests is working on github actions.

**Comment by harikt** [comment]
I just noticed this error poping up. Reopening it.

**Comment by harikt** [comment]
Now it is using `INTL_IDNA_VARIANT_UTS46` by default on 4.x. So hope this can be resolved for now.
