### ISSUE TITLE
What is the future of this project?

### ISSUE THREAD

**Issue by rotexdegba** [auraphp/Aura.Filter#141]
What is the future of this project? In my opinion, it is feature complete and only needs to have the latest versions of PHP (7.3, 7.4 & 8.0 as of this writing) tested via travis or Github Actions to ensure it continues to work with the currently supported version of PHP. Will anyone be updating the CI tests for this project?

**Comment by harikt** [comment]
Hi there,

CI is already updated. We will be releasing 4.x versions that support 7.4 to 8.1 as of now.
