### ISSUE TITLE
composer.json of master

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Filter#2]
1 ) composer.json of master is wrong one . Please update with that of the recent develop, so we can submit to packagist .

2 ) Now showing forked from pmjones . 

Have you submitted to github guys a ticket or we can make it as we did for Aura.Uri ?

**Comment by pmjones** [comment]
Are we still having trouble with this? If so, tell me what needs to happen (or send a pull request :-).

**Comment by harikt** [comment]
This has been merged to develop branch. But not to master .

The version currently written is `"version": "1.0.0-dev",` which is not the case , so we can change to `dev-master` 

https://github.com/auraphp/Aura.Filter/blob/develop/composer.json#L11

`"minimum-stability": "dev",` not added as in develop 

https://github.com/auraphp/Aura.Filter/blob/develop/composer.json#L19

autoload via composer itself is added 

https://github.com/auraphp/Aura.Filter/blob/develop/composer.json#L23

If you need a commit to master I will send , but not now . I will be moving to office shortly .

**Comment by pmjones** [comment]
Are we OK now?

**Comment by harikt** [comment]
I feel we are ok now. If there is any issue I will open :) .
