### ISSUE TITLE
Translator error on inValues filter fail

### ISSUE THREAD

**Issue by alwynn** [auraphp/Aura.Filter#29]
Translator triggers an error with message "PHP Notice:  Array to string conversion in vendor/aura/filter/src/Aura/Filter/Translator.php on line 72" when the "inValues" filter fails to pass.

Test case:

``` php
$values = range(0, 9);
$object = (object) [
    'field' =>11
];

$filter = require 'vendor/aura/filter/scripts/instance.php';
$filter->addSoftRule('field', $filter::IS, 'inValues', $values);
$filter->values($object);
```

Full error:

```
Notice: Array to string conversion in vendor/aura/filter/src/Aura/Filter/Translator.php on line 72

Call Stack:
    0.0001     227464   1. {main}() test.php:0
    0.0045    1053584   2. Aura\Filter\RuleCollection->values() test.php:12
    0.0046    1056192   3. Aura\Filter\RuleCollection->addMessage() vendor/aura/filter/src/Aura/Filter/RuleCollection.php:365
    0.0046    1056520   4. Aura\Filter\Translator->translate() vendor/aura/filter/src/Aura/Filter/RuleCollection.php:418
    0.0046    1057088   5. str_replace() vendor/aura/filter/src/Aura/Filter/Translator.php:72
```

**Comment by harikt** [comment]
Hi @alwynn ,

Thank you for the bug report and code. I did looked what is happening at the end. As I didn't get enough time to check why there is a need of making array of values in `setParams` we want to wait for @pmjones ( He is travelling and may be we want to wait for a while or if I get some time I surely will check and give a PR or if you find it do give a PR ) .

In the mean time if you need a quick fix, comment the below line and make the change in `src/Aura/Filter/Rule/InValues.php` . And this will also effect the `inKeys` .

``` php
// $this->setParams(['values' => array_values($array)]);
$this->setParams(array_values($array));
```

Thank you

**Comment by dhaaker** [comment]
I've just ran into the same problem. 
FYI, the quick fix I use.

/src/Aura/Filter/Translator.php, line 72

```
         // do string replacements
         foreach ($tokens_values as $token => $value) {
+            
+            if (! is_scalar($value)) {
+                $value = '';
+            }
+            
             $message = str_replace('{' . $token . '}', $value, $message);
         }
```

I would like to make a more solid patch with tests and all, but need some guidance (from @pmjones) on the desired direction to handle this issue.

**Comment by pmjones** [comment]
@dhaaker @alwynn Ah yes, I see the problem.  Using an empty string for the replacement value seems troublesome, mostly because seeing an empty value in the message makes it sound like there's no value. I'll take a look at this more closely.

**Comment by pmjones** [comment]
@dhaaker Your suggested patch looks good as a start. May I suggest the following expanded version?

```
    foreach ($tokens_values as $token => $value) {
        // convert an array to a CSV string
        if (is_array($value)) {
            $value = '"' . implode('", "', $value) . '"';
        }
        $message = str_replace('{' . $token . '}', $value, $message);
    }
```

**Comment by pmjones** [comment]
This appears to be fixed in https://github.com/auraphp/Aura.Filter/commit/2f4623be373832894db600da4fa866b6cb4b01a5 .  I will make a similar change to Aura.Intl to match this.

**Comment by harikt** [comment]
@pmjones I think we need to write a test case here, else we may go wrong at some other point.

**Comment by harikt** [comment]
It also will happen for `InValues` . Your solution is only for `InKeys` I guess.

**Comment by pmjones** [comment]
You are wise to ask about tests. A case is already in place, although not obvious: 

https://github.com/auraphp/Aura.Filter/blob/develop/tests/Aura/Filter/RuleCollectionTest.php#L257

**Comment by pmjones** [comment]
It's on both inKeys and on inValues.

**Comment by harikt** [comment]
Great! :+1:  .
