### ISSUE TITLE
Filter should use exceptions

### ISSUE THREAD

**Issue by mbrevda** [auraphp/Aura.Filter#34]
Validating code ends up requiring lots of if statements. Filter should be callable without worrying about its response, with exceptions throw to halt execution, when necessary.

for example:
Boilerplate:

``` php
$this->filter(...);
$data = ['foo' => 'bar'];
```

Before:

``` php
$success = $filter->values($data);
if (! $success) {
    $messages = $filter->getMessages();
    // do something with $messages;
}
```

After:

``` php
// exceptions can be caught anywhere in the stack
$filter->values($data);
```

**Comment by harikt** [comment]
I don't think so.

**Comment by pmjones** [comment]
Wish granted! See the new develop-2 work, via `__invoke()`, where a `FilterFailed` exception is thrown.

**Comment by mbrevda** [comment]
So now filters can be called either as invokables **or** with `->getValues()`, correct? (In my current stack, I specifically DONT want an exception thrown...)

**Comment by pmjones** [comment]
Or as ->values(), yes. Only __invoke() will throw the exception.

**Comment by mbrevda** [comment]
perfect
