### ISSUE TITLE
Configuring RuleCollection for use with Aura.Di

### ISSUE THREAD

**Issue by djmattyg007** [auraphp/Aura.Filter#38]
How would you recommend configuring the dependency injection container in the Aura.Di package for use with Aura.Filter's RuleCollection and RuleLocator classes? I've been trying to work it out for a few days and keep getting stuck. Are you able to provide an example?

**Comment by harikt** [comment]
Hey @djmattyg007 ,

If you are using Aura.Di v2 , then have a look into the configuration of https://github.com/auraphp/Aura.Filter/blob/develop/config/Common.php#L11 .

Have a look into https://github.com/auraphp/Aura.Filter/blob/develop/config/Common.php#L21 
and you need to either pass the object of type `TranslatorInterface` see https://github.com/auraphp/Aura.Filter/blob/develop/src/Aura/Filter/RuleCollection.php#L131 .

There is one already in filter https://github.com/auraphp/Aura.Filter/blob/develop/src/Aura/Filter/Translator.php .

if you are interested to use Aura.Filter and Aura.Intl see https://github.com/friendsofaura/FOA.Filter_Intl_Bundle .

Let me know if you need any more help on this.

**Comment by harikt** [comment]
@djmattyg007 does my comments help you?

Can we close this issue if you are satisfied?

Thank you

**Comment by harikt** [comment]
@djmattyg007 I am closing this. If you have still trouble please re-open.

Thank you.
