### ISSUE TITLE
please for all repos let's remove the wiki tab

### ISSUE THREAD

**Issue by cordoval** [auraphp/Aura.Filter#41]

**Comment by harikt** [comment]
@cordoval what do you mean by remove the wiki tab?

**Comment by cordoval** [comment]
![screenshot 2014-05-26 20 43 49](https://cloud.githubusercontent.com/assets/328359/3086713/6cf81930-e540-11e3-9747-86bad40cf2ba.png)
![screenshot 2014-05-26 20 43 56](https://cloud.githubusercontent.com/assets/328359/3086714/70bc74a8-e540-11e3-9792-b0d7e8755d68.png)

**Comment by harikt** [comment]
Though I don't get the usefulness of removing the wiki tab, I have un checked it for we are not using it :) . Hope that helps you.
