### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Filter#43]
One thing I like in v2 is usage of

``` php
$email = new Aura\Filter\Email('email@example.com');
$email->isValid();
```

like interface. I am not sure whether this is possible currently.

But just a wishlist . The idea is usage of filters in DDD as Mathias Verras mentioned in some slides. So we don't need to inject anything to factory or use it.

**Comment by harikt** [comment]
@cordoval would you like to look into this ?

**Comment by cordoval** [comment]
link me to Matthias Verraes references since they are many i want to know what you had in mind in particular

**Comment by cordoval** [comment]
so you see me as a genius? :blush: i shall concede your wish then, cc/ @pmjones

**Comment by harikt** [comment]
https://www.youtube.com/watch?v=ZJ63ltuwMaE , the example is same as the one shown.

**Comment by cordoval** [comment]
I just had a workshop yesterday where he taught me everything cc/ @mathiasverraes :blush: just kidding

**Comment by mathiasverraes** [comment]
Email filter != email value object

**Comment by cordoval** [comment]
i heard this explanation from your friend yesterday, about causation, is this related?
he was saying that because of causation i couldn't do a refactor of some method and do composition of some helper function. i know i am mixing things but if you can respond :blush: would be great, just pour some thoughts on what is causation at least, or maybe i can ask on the mailing list.

**Comment by harikt** [comment]
Thank you @mathiasverraes  for being here. So if say 

``` php
class EmailValueObject 
{
    public function __construct($email) 
    {
        $emailfilter = new Aura\Filter\Email($email);
        $emailfilter->isValid();
    }
}
```

My ideas was usage like the above. Probably I am wrong for I my need to use dependency injection of the email filter here.

``` php
class EmailValueObject 
{
    public function __construct($emailfilter, $email) 
    {
        $this->emailfilter = $emailfilter;
        $this->emailfilter->isValid($email);
    }
}
```

But this seems more overhead I am doing.

And may be the filter itself throws exception.

UPDATE : 

Also in v1 this is doable  https://github.com/auraphp/Aura.Filter/tree/develop#applying-rules-to-individual-values

But you could not call it like the above. Eg below

``` php
// an individual value
$username = 'new_username';

// filter the individual value
$success = $filter->value($username, $filter::IS, 'alnum');
if (! $success) {
    echo "Username is not alphanumeric.";
}
```

This is why I am looking to create objects individually in v2.

**Comment by mathiasverraes** [comment]
causation: Totally unrelated :-)

On 27 June 2014 09:48, Luis Cordova notifications@github.com wrote:

> i heard this explanation from your friend yesterday, about causation, is
> this related?
> he was saying that because of causation i couldn't do a refactor of some
> method and do composition of some helper function. i know i am mixing
> things but if you can respond [image: :blush:] would be great, just pour
> some thoughts on what is causation at least, or maybe i can ask on the
> mailing list.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/auraphp/Aura.Filter/issues/43#issuecomment-47316712.

## 

Mathias Verraes
mathias@verraes.net
http://verraes.net
@mathiasverraes http://twitter.com/mathiasverraes

**Comment by mathiasverraes** [comment]
final class Email // value object
{
   construct($email)
       if(!Email::isvalid($email)) throw InvalidArgument
       $this->email = $email
}

But the email value object would not be part of your filter library at all
the goal of the email value object is not to validate, that's only a side
effect of the concept of protecting your own consistency boundary
The goal of the email VO is to BE an email.

On 27 June 2014 09:54, Mathias Verraes mathias@verraes.net wrote:

> causation: Totally unrelated :-)
> 
> On 27 June 2014 09:48, Luis Cordova notifications@github.com wrote:
> 
> > i heard this explanation from your friend yesterday, about causation, is
> > this related?
> > he was saying that because of causation i couldn't do a refactor of some
> > method and do composition of some helper function. i know i am mixing
> > things but if you can respond [image: :blush:] would be great, just pour
> > some thoughts on what is causation at least, or maybe i can ask on the
> > mailing list.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/auraphp/Aura.Filter/issues/43#issuecomment-47316712.
> 
> ## 
> 
> Mathias Verraes
> mathias@verraes.net
> http://verraes.net
> @mathiasverraes http://twitter.com/mathiasverraes

## 

Mathias Verraes
mathias@verraes.net
http://verraes.net
@mathiasverraes http://twitter.com/mathiasverraes

**Comment by harikt** [comment]
I have updated my above explanation of the example of v1 and v2.

From your example

``` php
final class Email // value object 
{ 
    public function __construct($email)
    {
        if(!Email::isvalid($email)) throw InvalidArgument 
        $this->email = $email 
    }
}
```

there is no `isValid($email)` defined.

And I am interested in this part only. 

``` php
public function isValid($email)
{
    $filter = new Aura\Filter\Email($email);
    return $filter->isValid();
}
```

See the updated comment with v1 and v2 usage. I would like to bring consistency in v1 and v2, and usage of not injecting all the dependencies to RuleCollection https://github.com/auraphp/Aura.Filter/blob/develop/scripts/instance.php . 

Thanks

**Comment by pmjones** [comment]
@harikt I think your wish has been granted, to some extent. E.g.:

```
$rule = new \Aura\Filter\Rule\Validate\Email();
if ($rule($this, 'email_property') {
    // $this->email_property is valid
} else {
    // $this->email_property is not valid
}
```

Alternatively, you can pass in a ValueFilter and use that:

```
if ($value_filter->validate($email_value, 'email')) {
    // valid
} else {
    // not valid
}
```

(The new `$subject->$field` notation in the rules precludes validating a single value outside of an object, thus the need for ValueFilter.)

**Comment by harikt** [comment]
I think I love the second one. The reason is you may not no when passing objects the field property is private, public etc . So to work on all cases I prefer 2nd. 

Thank you Paul.
