### ISSUE TITLE
Why SanitizeLocator and ValidateLocator ?

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Filter#59]
Why not a single locator for both `SanitizeLocator`  and `ValidateLocator` has no special methods needed.

**Comment by pmjones** [comment]
I had it that way to begin with, but as a convenience for DI containers, it's nice to be able to specify separate locators for separate types of rules.

**Comment by harikt** [comment]
aah I get you :) . 

Thank you for the explanation.
