### ISSUE TITLE
Validation arguments should be constants

### ISSUE THREAD

**Issue by brandonsavage** [auraphp/Aura.Filter#61]
We are currently allowing users to validate by using a string value to indicate the validator they wish to use:

``` php
$filter->validate('credit_card')->is('creditCard');
```

For built-in validators, we should instead use constants:

``` php
$filter->validate('credit_card')->is(Filter::CREDIT_CARD);
```

**Comment by pmjones** [comment]
Good call. They'd need to be replaced in the FilterFactory and in the Config as wel.

**Comment by brandonsavage** [comment]
Now, the issue comes if the user defines custom filters/validators, but we can solve that by creating a class of constants and the user can extend it. Let's discuss it next week in the channel.

**Comment by pmjones** [comment]
I've tried this out and I just don't like the way it looks/feels when writing the rules.

``` php
use Aura\Filter\Rule\Rule;

$filter->validate('field')->is(Rule::STRLEN_BETWEEN, 6, 10);
// vs
$filter->validate('field')->is('strlenBetween', 6, 10);
```

I reserve the right to change my mind later.

**Comment by koriym** [comment]
Already closed, But I would like to drop my +1 for this proposal by @brandonsavage.
It helps autocomplete typing.

**Comment by pmjones** [comment]
All right, then, that's two opinions to one. Let me see what I can do. :-)

**Comment by brandonsavage** [comment]
Paul, feel free to show me what you've got so far and maybe I can help.

**Comment by pmjones** [comment]
Take a look at the newest 2.x work (released yesterday).

**Comment by brandonsavage** [comment]
I meant did you already have an example of attempting constants?

**Comment by pmjones** [comment]
Ah! Just re-added the class of constants I tried out earlier, in a new branch : https://github.com/auraphp/Aura.Filter/tree/constants

**Comment by harikt** [comment]
Is there any issues if we keep both constants and string values ?

So the users can use what they need.

**Comment by pmjones** [comment]
> Is there any issues if we keep both constants and string values ?

Since the constants are strings, they end up being the same thing, so yes.

**Comment by koriym** [comment]
@pmjones @brandonsavage nice ! thanks.

**Comment by brandonsavage** [comment]
@pmjones, what about that organization structure do you dislike?

**Comment by pmjones** [comment]
It's the difference between this ...

``` php
use Aura\Filter\Filter;
use Aura\Filter\FilterFactory;

$filter_factory = new FilterFactory();
$filter = $filter_factory->newSubjectFilter();

$filter->validate('password')->is(Filter::EQUAL_TO_FIELD, 'password_confirm');
```

... and this:

``` php
use Aura\Filter\FilterFactory;

$filter_factory = new FilterFactory();
$filter = $filter_factory->newSubjectFilter();

$filter->validate('password')->is('equalToField', 'password_confirm');
```

Further, when writing custom rules, one now needs to extend Filter as well, to incorporate a new constant, or mix constants with literal strings. First, adding the constant somewhere meaningful:

``` php
use Aura\Filter\Filter;

class MyFilter extends Filter
{
    const HEX = 'hex';
}
```

Then create the custom rules [per the examples](https://github.com/auraphp/Aura.Filter/blob/2.x/docs/custom.md#writing-a-rule-class), then add them to the factories with the constant:

``` php
use MyFilter;
use Aura\Filter\FilterFactory;

$validate_factories = array(
    MyFilter::HEX => function () { return new Vendor\Package\Filter\Rule\Validate\ValidateHex(); },
);

$sanitize_factories = array(
    MyFilter::HEX => function () { return new Vendor\Package\Filter\Rule\Sanitize\SanitizeHex(); },
);

$filter_factory = new FilterFactory(
    $validate_factories,
    $sanitize_factories
);

$filter->validate('color')->is(MyFilter::HEX, 6);
```

In all, daily use just seems easier to go with string literals than constants. It's one less thing to worry about.

**Comment by pmjones** [comment]
Overall I just don't like this approach. Do you still think it's a big deal?

**Comment by koriym** [comment]
> when writing custom rules, one now needs to extend Filter as well, to incorporate a new constant, or mix constants with literal strings
> ...
> In all, daily use just seems easier to go with string literals than constants. It's one less thing to worry about.

@pmjones I understand. The coding become more vary as you shown.  Although I still prefer constants, The original method seems more Aura-way.

**Comment by mivanov93** [comment]
The constants idea seems fine. Considering this:

```
use MyFilter;
use Aura\Filter\FilterFactory;

$validate_factories = array(
    MyFilter::HEX => function () { return new Vendor\Package\Filter\Rule\Validate\ValidateHex(); },
);

$sanitize_factories = array(
    MyFilter::HEX => function () { return new Vendor\Package\Filter\Rule\Sanitize\SanitizeHex(); },
);

$filter_factory = new FilterFactory(
    $validate_factories,
    $sanitize_factories
);

$filter->validate('color')->is(MyFilter::HEX, 6);
```

Seems that we need the additional MyFilter class anyway, but otherwise we'd still have to:

```
use Aura\Filter\FilterFactory;

$validate_factories = array(
    'hex'=> function () { return new Vendor\Package\Filter\Rule\Validate\ValidateHex(); },
);

$sanitize_factories = array(
    'hex' => function () { return new Vendor\Package\Filter\Rule\Sanitize\SanitizeHex(); },
);

$filter_factory = new FilterFactory(
    $validate_factories,
    $sanitize_factories
);
```

and

```
$filter->validate('color')->is(MyFilter::HEX, 6);
```

vs

```
$filter->validate('color')->is('hex', 6);
```

So I see no savings except for MyFilter::HEX vs 'hex', but we could map MyFilter as something shorter :), like F, and then since it has a namespace we can get out of collisions and still preserve the meaning. SInce we will do something like `use ....\MyFilter as F;`

Also if we need custom filters, we might as well name them and make a class for them.
It's harder to make a mistake with a missing constant/also autocomplete.

Also what about the following(I haven't tested but it should be fine I think):

```
use Aura\Filter\Filter;

class MyFilter extends Filter
{
    const HEX = 'hex';
    public static $validate=array(self::HEX => function() { return new ....; });
    public static $sanitize=array(self::HEX => function() { return new ....; });
}


use MyFilter;
use Aura\Filter\FilterFactory;

$filter_factory = new FilterFactory(
    MyFilter::validate,
    MyFilter::sanitize
);
$filter->validate('color')->is(MyFilter::HEX, 6);
```

so we use the additional class to statically create our validation factories.

**Comment by mivanov93** [comment]
Thoughts, anyone?

**Comment by pmjones** [comment]
I continue to not-like it.

**Comment by brandonsavage** [comment]
I don't like it as much as I thought I would either.

**Comment by mivanov93** [comment]
What negative points are there to it? Can you elaborate? IMHO seems like a small addition that won't increase complexity and will add very minimal overhead, while saving time and guarding from errors(autocomplete).

**Comment by pmjones** [comment]
It _seems_ like that, in theory, but actual use of it on a regular basis is ... not compelling.

**Comment by pmjones** [comment]
While this sounds nice in theory, in practice it turns out to be cumbersome. Even the original submitter is no longer convinced it's a good idea. Closing this until further practice shows otherwise.
