### ISSUE TITLE
Update readme for Instantiation. Method newFilter() missing in FilterFactory

### ISSUE THREAD

**Issue by swarajgiri** [auraphp/Aura.Filter#67]
Instantiation in read me says

``` php
<?php
use Aura\Filter\FilterFactory;

$filter_factory = new FilterFactory();
$filter = $filter_factory->newFilter();
?>
```

But `newFilter()` is not a method available in `FilterFactory` class
Basically, almost all of the read me needs to be updated to reflect the new usage

**Comment by Isotab** [comment]
If you switch the branch from develop-2 to develop or master you will see an updated read me

**Comment by swarajgiri** [comment]
That works.
Would help if we could have a link to the [Manuals](http://auraphp.com/manuals/v1/en/filter/).

**Comment by harikt** [comment]
You have see http://auraphp.com/packages/Aura.Filter/

**Comment by pmjones** [comment]
This looks like it's resolved; please let me know if it's not, or (preferably) open a PR with a fix. Thanks!
