### ISSUE TITLE
Sorry to ask for a release, but

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Filter#70]
Hi Paul,

I do understand that the v1 is EOL. But as v2 is not yet released also can you make one last release with the fix having the set message on the Translator.php ?

**Comment by harikt** [comment]
I am looking at https://github.com/auraphp/Aura.Filter/blame/1.x/src/Aura/Filter/Translator.php#L54

**Comment by pmjones** [comment]
Are you certain that this is not in the latest release? Please take a look to make sure.

**Comment by harikt** [comment]
The last release is 1.0.2 https://github.com/auraphp/Aura.Filter/blob/1.0.2/src/Aura/Filter/Translator.php which was in Aug 24, 2014

**Comment by pmjones** [comment]
I just released 1.1.0.
