### ISSUE TITLE
Closure filtering should allow any callable instead

### ISSUE THREAD

**Issue by auroraeosrose** [auraphp/Aura.Filter#71]
The closure filtering is typehinting using Closure, this means that callable methods or functions from elsewhere cannot be used

Using the Callable typehint instead (available since 5.4) would allow any legal callable to be used instead (and would require no code changes except the typehint)

**Comment by harikt** [comment]
@auroraeosrose I hope you are using the 2.x branch ? .

**Comment by auroraeosrose** [comment]
yes

**Comment by harikt** [comment]
May be you could send a PR, so Paul could look and merge.

Thank you.

**Comment by pmjones** [comment]
Good call. Would we be ok renaming the classes from `(Sanitize|Validate)\Closure` to ``(Sanitize|Validate)\Callback` in line with that change?

**Comment by pmjones** [comment]
@auroraeosrose ^

**Comment by auroraeosrose** [comment]
callback or callable?  ah naming things - doesn't matter too much

**Comment by pmjones** [comment]
Callable is reserved, so callback. I take that to mean a rename in general is not a problem.
