### ISSUE TITLE
Rules `Now` is in factories but does not exists...

### ISSUE THREAD

**Issue by gmazzap** [auraphp/Aura.Filter#72]
In the `FilterFactory` class there is the array for all rule classes.

Among the factories there is the one for the rule [`now`](https://github.com/auraphp/Aura.Filter/blob/2.x/src/FilterFactory.php#L119) that create an instance of the class `Aura\Filter\Rule\Validate\Now`.

Problem is that class [does not exist](https://github.com/auraphp/Aura.Filter/tree/2.x/src/Rule/Validate)...

It exists a **sanitize** rule: [`Aura\Filter\Rule\Sanitize\Now`](https://github.com/auraphp/Aura.Filter/blob/2.x/src/Rule/Sanitize/Now.php), but not a **validate** one.

**Comment by harikt** [comment]
good catch.
