### ISSUE TITLE
Bool filters and rules do not handle non-scalar values properly

### ISSUE THREAD

**Issue by auroraeosrose** [auraphp/Aura.Filter#73]
There is no code to handle values that are non-scalar when sanitizing or validating booleans, instead it tries to pass the value directly through assuming it is scalar and throws php warnings

PHPUnit_Framework_Error_Warning: trim() expects parameter 1 to be string, array given in aura/filter/src/Rule/AbstractBool.php on line 45

**Comment by harikt** [comment]
Hey @auroraeosrose , 

Thank you for reporting the issue. May be you could see if the PR https://github.com/auraphp/Aura.Filter/pull/74 fits. or add any additional test case as needed ?

Thank you.

**Comment by auroraeosrose** [comment]
Looks good, thanks!
