### ISSUE TITLE
"Slug" Validation and Sanitization?

### ISSUE THREAD

**Issue by jakejohns** [auraphp/Aura.Filter#86]
This might be 'too particular a use case', but I often find myself "sluggifying"
strings or checking strings for "slugginess".

Is there space for something like this?

I didn't submit a PR, since I thought I'd see what people thought before wasting
too much time. (Also, not sure I know the best way to deal with various out of
bound characters)

Alternatively, it may be better for me to just write something to integrate
aura/filter with some existing solution.

Most implementations of stuff like this are much more robust that what I'm
including as basic illustration of concept. Most handle things like transcoding
certain characters, take some amount of configuration, etc.
### Handful of examples:
- [cocur/slugify](https://github.com/cocur/slugify)
- [Stringy::slugify](https://github.com/danielstjules/Stringy/blob/master/src/Stringy.php#L810)
- [Laravel Str::slug](https://github.com/illuminate/support/blob/master/Str.php#L351)
- [Behat Transliterator::urlize](https://github.com/Behat/Transliterator/blob/master/src/Behat/Transliterator/Transliterator.php#L383)
- [kevinlebrun/slug.php](https://github.com/kevinlebrun/slug.php)
### Basic Validate

``` php
namespace Aura\Filter\Rule\Validate;

class Alnum
{
    public function __invoke($subject, $field)
    {
        $value = $subject->$field;
        if (! is_scalar($value)) {
            return false;
        }

        return preg_match('/^[a-z][-a-z0-9]*$/', $value);
    }
}
```
### Basic Sanitize

``` php
namespace Aura\Filter\Rule\Sanitize;

class Slug
{
    public function __invoke($subject, $field)
    {
        $value = $subject->$field;
        if (! is_scalar($value)) {
            return false;
        }

        $value = preg_replace('/[^a-z0-9-]+/', '-', strtolower($value));
        $value = preg_replace("/-+/", '-', $value);
        $value = trim($value, '-');

        $subject->$field = $value;
        return true;
    }
}
```

Thoughts?

**Comment by harikt** [comment]
Hi @jakejohns interesting proposal and thanks for all the links to different implementations.

The slugify seems a complex task to me ( See https://github.com/Behat/Transliterator/tree/master/src/Behat/Transliterator/data ). And I am not sure other libraries all come up same rules. So validating / sanitizing seems out of scope and it depends on library implementations I think.

else the validator will pass just simple rules and the implementation may have different one. 

Anyway it is nice to have one if we can cover all the rules.

Thank you.

**Comment by jakejohns** [comment]
I assume that there is some degree of variation among the linked
implementations. I would not think a set of "slug rules" in aura/filter would
necessarily accommodate all or any specific implementations. Rather, I would
think that aura would provide "it's own" implementation of the concept in line
with the elegance, standards, and principals of the project.

While the conversion in the Behat/Transliterator implementation you cite is
certainly robust, it is likely unnecessary for _many_ use cases.

[An example here on StackOverflow](http://stackoverflow.com/questions/2955251/php-function-to-make-slug-url-string#2955878)
is using iconv for transliteration purposes. eg.:

``` php
//...
// transliterate
$value = iconv('utf-8', 'us-ascii//TRANSLIT', $value);
$value = preg_replace('/[^a-z0-9-]+/', '-', strtolower($value));
$value = preg_replace("/-+/", '-', $value);
$value = trim($value, '-');
//...
```

Again, I would not think that an aura component would necessarily be able to
validate or create a "slug" which complies with other implementations. 
The only real requirement would be that a string 'aura slug sanitized' would
'aura slug validate'.

I suppose it's not **too** cumbersome to implement my own minimalist
version with the existing rules:

``` php
use Aura\Filter\FilterFactory;

$factory= new FilterFactory();
$valid = $factory->newSubjectFilter();
$sanit = $factory->newSubjectFilter();

$valid->validate('slug')->is('regex', '/^[a-z][-a-z0-9]*$/');

$sanit->sanitize('slug')
    ->to(
        'callback',
        function ($subject, $field) {
            $subject->$field = strtolower(
                iconv(
                    'utf-8',
                    'us-ascii//TRANSLIT',
                    $subject->$field
                )
            );
            return true;
        }
    );
$sanit->sanitize('slug')->to('regex', '/[^a-z0-9-]+/', '-');
$sanit->sanitize('slug')->to('regex', '/-+/', '-');

$subject = (object) ['slug' => 'naïve slug hôtel in Québec'];

var_dump($sanit->apply($subject));
var_dump($valid->apply($subject));
```

(or more likely all that in a single callback rule)

Perhaps the concept is too nebulous 
to provide a concrete implementation in aura.

**Comment by harikt** [comment]
Thanks again @jakejohns for your explanations.

**Comment by pmjones** [comment]
Tell you what @jakejohns -- write a validate and sanitize rule for your own use. Use it for a while, and when you feel like your own usage has proved its worth, submit it back here as a PR. That sounds reasonable?

**Comment by jakejohns** [comment]
Certainly. Sounds like a plan.

**Comment by pmjones** [comment]
Closing per the above comment; please open a new PR when you have a candidate slug filter ready-to-share.

**Comment by harikt** [comment]
Another one to add into the list : https://github.com/keyvanakbary/slugifier
