### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by mivanov93** [auraphp/Aura.Filter#94]
Currently, it's acceptable to have numbers in the top level domain. Which should only be used for internationalized domains(starting with xn-- as stated in https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains

Ex. alpha@example.com1 should be invalid, but it's not.

Com1 doesn't start with xn and is not an internationalized domain either.

It's okay to be able to use an IP instead of a domain name(ex. 123@1.2.3.4), but not a mix of both.

Also, as far as I know domains must be at least 2 symbols long(did a search). Hence:
alpha@example.c should be invalid as well.

Another thing is - what about strong email validation using https://secure.php.net/manual/en/function.checkdnsrr.php

Since it makes a network call, maybe it should be in another rule, EmailMX or something.

**Comment by pmjones** [comment]
What about this as a replacement?

http://stackoverflow.com/questions/201323/using-a-regular-expression-to-validate-an-email-address/1917982#1917982

The PHP code would be:

``` php
$regex = <<<REGEX
/^(?(DEFINE)
   (?<address>         (?&mailbox) | (?&group))
   (?<mailbox>         (?&name_addr) | (?&addr_spec))
   (?<name_addr>       (?&display_name)? (?&angle_addr))
   (?<angle_addr>      (?&CFWS)? < (?&addr_spec) > (?&CFWS)?)
   (?<group>           (?&display_name) : (?:(?&mailbox_list) | (?&CFWS))? ;
                                          (?&CFWS)?)
   (?<display_name>    (?&phrase))
   (?<mailbox_list>    (?&mailbox) (?: , (?&mailbox))*)

   (?<addr_spec>       (?&local_part) \@ (?&domain))
   (?<local_part>      (?&dot_atom) | (?&quoted_string))
   (?<domain>          (?&dot_atom) | (?&domain_literal))
   (?<domain_literal>  (?&CFWS)? \[ (?: (?&FWS)? (?&dcontent))* (?&FWS)?
                                 \] (?&CFWS)?)
   (?<dcontent>        (?&dtext) | (?&quoted_pair))
   (?<dtext>           (?&NO_WS_CTL) | [\x21-\x5a\x5e-\x7e])

   (?<atext>           (?&ALPHA) | (?&DIGIT) | [!#\$%&'*+-\/?^_`{|}~])
   (?<atom>            (?&CFWS)? (?&atext)+ (?&CFWS)?)
   (?<dot_atom>        (?&CFWS)? (?&dot_atom_text) (?&CFWS)?)
   (?<dot_atom_text>   (?&atext)+ (?: \. (?&atext)+)*)

   (?<text>            [\x01-\x09\x0b\x0c\x0e-\x7f])
   (?<quoted_pair>     \\ (?&text))

   (?<qtext>           (?&NO_WS_CTL) | [\x21\x23-\x5b\x5d-\x7e])
   (?<qcontent>        (?&qtext) | (?&quoted_pair))
   (?<quoted_string>   (?&CFWS)? (?&DQUOTE) (?:(?&FWS)? (?&qcontent))*
                        (?&FWS)? (?&DQUOTE) (?&CFWS)?)

   (?<word>            (?&atom) | (?&quoted_string))
   (?<phrase>          (?&word)+)

   # Folding white space
   (?<FWS>             (?: (?&WSP)* (?&CRLF))? (?&WSP)+)
   (?<ctext>           (?&NO_WS_CTL) | [\x21-\x27\x2a-\x5b\x5d-\x7e])
   (?<ccontent>        (?&ctext) | (?&quoted_pair) | (?&comment))
   (?<comment>         \( (?: (?&FWS)? (?&ccontent))* (?&FWS)? \) )
   (?<CFWS>            (?: (?&FWS)? (?&comment))*
                       (?: (?:(?&FWS)? (?&comment)) | (?&FWS)))

   # No whitespace control
   (?<NO_WS_CTL>       [\x01-\x08\x0b\x0c\x0e-\x1f\x7f])

   (?<ALPHA>           [A-Za-z])
   (?<DIGIT>           [0-9])
   (?<CRLF>            \x0d \x0a)
   (?<DQUOTE>          ")
   (?<WSP>             [\x20\x09])
 )

 (?&address)$/x
REGEX;

$email = 'foo@bar.com';
var_dump(preg_match($regex, $email));
```

Thoughts?

**UPDATE:** Add `^` and `$` to the regex to force it to match the entire string as an email address, not just any subsection as an email address.

**Comment by harikt** [comment]
First thoughts were regex why ( Reason not for regex : not as easy to understand to everyone ) . Then I had a look at the function requirement https://secure.php.net/manual/en/network.requirements.php , bind to Linux. So it seems nice to go with regex as suggested by @pmjones :-) .

**Comment by harikt** [comment]
There is another library if you guys are interested . 

https://github.com/dominicsayers/isemail which is being ported to  https://github.com/egulias/EmailValidator

May be we keep wrapper ?

**Comment by mivanov93** [comment]
@pmjones 
It's not working correctly, tried it and we are getting:
nonalpha@example.c as valid,(single letter domain)
non:alpha@example.com as valid(colon)
something @ somewhere.edu as valid(whitespace)

**Comment by mivanov93** [comment]
@harikt 

That could work, but isn't it a bit of an overkill?

Plus the idea of Aura is to escape external deps,
and if it goes this way - sometime in the future it could easily depend
on 10 other libraries for validation of urls, emails, etc.

Also I wonder, is email validation something that requires such complexity. But then again,
when looking at the code - it seems it's not more complex than it should be, considering the lengthy email specification.

**Comment by pmjones** [comment]
@mivanov93 Are you certain those are invalid email addresses, per the RFC? https://tools.ietf.org/html/rfc5322#section-3.4

**Comment by pmjones** [comment]
Oh hold on -- that regex finds a valid email in the given string, but does not say _the entire string_ is a valid email. One second, let me update it.

**Comment by pmjones** [comment]
OK, I have updated the above regex. Take another look, see if it works for you, and per the spec.

**Comment by mivanov93** [comment]
Still detects:
nonalpha@example.c as valid,(single letter domain)
something @ somewhere.edu as valid(whitespace)

Maybe nonalpha@example.c is valid since the email spec doesn't take the current TLD's into account, hence it looks valid.(Maybe someday we will have 1 letter TLD's).

But as far as whitespace is concerned, it shouldn't be allowed.

**Comment by pmjones** [comment]
/me nods

I wonder if there's a collection of email test addresses somewhere we could use to tune it.

**Comment by mivanov93** [comment]
We should test this:
http://isemail.info/about

As for lists:
http://code.iamcal.com/php/rfc822/tests/
https://fightingforalostcause.net/content/misc/2006/compare-email-regex.php

By the way I've tried the internal filter_var but it's not good enough either.

**Comment by harikt** [comment]
> That could work, but isn't it a bit of an overkill?

@mivanov93 As I mentioned it is just a wrapper class. Say 

``` php
class IsEmailValidator ...
{
    {
          // check with is_email
    }
} 
```

We only suggest the package for users who want to really do such validations. Though I don't know whether @pmjones like that or not.

**Comment by mivanov93** [comment]
Well, that adds a bit of complexity, but the way I see it - we have 3 viable options:

*a) we leave the validation incomplete, as it is now
*b) we add some external library(optional dependency) Cons: Aura will have to check for that library, and it must have a constant interface, but since that's not the case, we will basically introduce an separate bridge, so then we will have an Aura.Bridge :laughing: maintaining constant interfaces for random libraries. And here goes Legacy Hell.
*c) we copy the library into Aura.Filter basically merging them and maintain it as part of Aura.Filter
unattached to the original library. Cons: duplicating code, reinventing the wheel. Pros: The email specification probably won't be change anytime soon, hence said code is rather static, so mostly it will be bugfixes if anything.
d) we basically copy the code from that library, but putting in an a single class or some other ridiculously long is_email function, which is quite unreadable, so it's like using a binary/blackbox instead of a library to rid us of the feeling of introducing abstraction through multiple classes/interfaces/etc.. Worst option and basically a roundabout way to fail at c)

Personally I'm against b) and d), probably c) would be my choice. Since validating is what Aura.filter should do, and it should be standalone. So delegating different validations to other libraries will fragment it.

**Comment by mivanov93** [comment]
Thoughts?

**Comment by pmjones** [comment]
I think option (c) seems reasonable. @dominicsayers is the controlling party though.

Dominic, would you object to a fork of your BSD-licensed `is_email()` code into a likewise BSD-licensed project, to be maintained separately by us as a class instead of as a function, retaining full attribution to you and the other contributors? (The primary driving force here is that Aura avoids implementation dependencies, so merely adding a dependency on `is_email()` is precluded by the Aura project goals.)

**Comment by dominicsayers** [comment]
Absolutely no objection at all. Please go ahead.

Dominic

**Comment by pmjones** [comment]
@dominicsayers That's great news. I can run the final product by you when it's done, if you like, to make sure it meets good form. Thanks!

**Comment by pmjones** [comment]
@mivanov93 I have created an "isemail" branch for this feature and imported the is_email() code as-is from the dominicsayers/isemail repo.

The next task is to import the is_email() tests from dominicsayers/isemail so we can refactor safely. Can you deal with that? (It's not a trivial task.)

**Comment by mivanov93** [comment]
I think so, but should we retain the idea of using XML's for the test data instead of hardcoding in in the tests?(like it's done in Aura). Also the way I see it - is_email allows multiple levels of validation, unlike Aura's validate based on the simple idea of true and false. Hence I am wondering if it would be simple to group all the invalid emails and all the valid emails in two lists and just compare with that without bothering with the fact whether x or y has failed, but that some check has failed or none at all. Unless we have multiple email validators allowing to set the fail threshold, we shouldn't use all the features of is_email but instead simplify it to a true/false.

**Comment by pmjones** [comment]
Leaving the XML in place for now seems reasonable.

I think leaving the levels of invalidation is also reasonable; internally, it might be useful to know what part failed. I can imagine allowing users to set the validation level.

Basically, keep everything as much the same as possible _for this initial import_ -- it's important to make sure that everything passes the same as it does in the original project. Only then should we consider any kinds of real changes.

**Comment by pmjones** [comment]
@mivanov93 @dominicsayers I have incorporated the is_email() function as a class method, and all of the tests, in the new branch https://github.com/auraphp/Aura.Filter/tree/isemail.

There are two bits of weirdness: test id 48 should pass as valid but does not, and test id 71 should not pass as valid but does. Any hints here are appreciated, as well as criticism about the incorporation process.

**Comment by pmjones** [comment]
FWIW, the email rule is at https://github.com/auraphp/Aura.Filter/blob/isemail/src/Rule/Validate/Email.php and the test is at https://github.com/auraphp/Aura.Filter/blob/isemail/tests/Rule/Validate/EmailTest.php.

**Comment by pmjones** [comment]
@mivanov93 The test all pass; the problem was using XML as text instead of a file. Please review the branch and try it for your use cases.

**Comment by pmjones** [comment]
@dominicsayers If you could review and see if I have screwed up anything obvious, i'd appreciate it. I know you're busy so ignore at will.

**Comment by pmjones** [comment]
FWIW, I have merged this branch to 2.x. @mivanov93 if you notice problems please let me know.
