### ISSUE TITLE
Discuss here the bugfix about the missing properties

### ISSUE THREAD

**Issue by mivanov93** [auraphp/Aura.Filter#97]
Quoting the new function from my commit(waiting for merge)

```
protected function applyRule($subject)
{
        $added = false;
        $rule = $this->locator->get($this->rule);
        $args = $this->args;
        array_unshift($args, $this->field);
        array_unshift($args, $subject);
        if(!isset($subject->{$this->field}) && !property_exists($subject,$this->field))
        {
                 $subject->{$this->field} = null;
                 $added = true;
        }

        $result = call_user_func_array($rule, $args);
        if($added && property_exists($subject,$this->field) && $subject->{$this->field} === null) {
            unset($subject->{$this->field});
        }
        return $result;
    }
```

Cons: it will fail if you depend on it for add for example null to an array=>say we have $a=[];
and you expect to get $a=[b=>null]; out of it.

and the other options:

1) just return false in applyRule on missing property(not good imho), since the property could be allowed to be null. Hence obj={a:null} would be the same as obj={};(sorry for the json notation). So if obj->a can be null, then why can't obj->a be missing? Also if we for example want a remove rule, we should not get an error if it's already removed, right?

2) in all rules which don't allow null values=>do explicit isset/has_property(also those two are different) checks (too time consuming for me to do right now, but perhaps the best solution).

**Comment by harikt** [comment]
Is this discussion related to https://github.com/auraphp/Aura.Filter/pull/96 ? It may be good to keep the discussion on the same thread , so will not be missed on merge.

**Comment by pmjones** [comment]
Closing in favor of discussing at #96.
