### ISSUE TITLE
getDefaultMessage() error when using a Closure and the validation fails

### ISSUE THREAD

**Issue by jelofson** [auraphp/Aura.Filter#99]
Try the following:

```
$filter = $filter_factory->newSubjectFilter();
$filter->validate('age')->is('callback', function($s, $f) {
    return false;
});
// PHP Catchable fatal error:  Object of class Closure could not be converted to string in ... 
// filter/src/Spec/Spec.php on line 324
```

Seems that there should be a check to see if args is a Closure.

NOTE: if you use `asHardRule('whatever')` it works

```
// From Spec.php line 324ish
protected function getDefaultMessage()
{
    $message = $this->rule;
    if ($this->args) {
        $message .= '(' . implode(', ', $this->args) . ')';
    }
    return $message;
}
```

**Comment by harikt** [comment]
@pmjones will there be a fix for this as you push it for a release / stable one ?

**Comment by pmjones** [comment]
I think there would have to be, yes. PRs, anyone?

**Comment by pmjones** [comment]
Oh and nice to see you @jelofson  :-)

**Comment by harikt** [comment]
There is a problem in this, how can we fix this bug.

1 . The `$this->args` is the one that contains closure. So one fix is check if its callable and skip the implode. 
2 . Check in the $this->args if it is a closure and remove it.

Both don't have a proper message to give back as failure. May be ask to add a failure message  if it is callable ?
